spring:
  #datasource dynamic
  datasource:
    username: ${db.username}
    password: ${db.password}
    hikari:
      maximum-pool-size: ${db.maximum-pool-size}
      connection-timeout: ${db.connection-timeout}
    url: ${db.url}


  application:
    name: companies-crud
  profiles:
    #default: prod   #profile pro in production
    #name of profile in test
   default: default #name of profile
  config:
    import: "optional:configserver:http://localhost:7777"
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: update

server:
  servlet:
    context-path: /companies-crud
  port:  8081 #port:8081 รณ port:0
#config of Logg for traceability
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

