spring:
  application:
    name: companies-crud
  profiles:
    #default: prod   #profile pro in production
    #name of profile in test
   default: default #name of profile
  config:
    import: "configserver:http://localhost:7777"
  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${db.maximum-pool-size}
      connection-timeout: ${db.connection-timeout}
    initialization-mode: always

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  servlet:
    context-path: /companies-crud
  port:  8081 #port:8081 ó port:0
#config of Logg for traceability
logging:
  level:
    # Asegura que los logs INFO de tu paquete sean visibles
    upeu.edu.pe.companies_crud: INFO # O DEBUG si quieres más detalle aún
    # ... (tus otros niveles DEBUG que ya tenías)
    org.springframework.cloud.config.client: DEBUG
    org.springframework.cloud.bootstrap: DEBUG
    org.springframework.boot.context.config: DEBUG
    com.zaxxer.hikari: DEBUG
    # ... (tu config de SQL/Hibernate)
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

